CREATE TABLE benutzer (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    benutzername VARCHAR(100) NOT NULL UNIQUE,
    passwort   VARCHAR(255) NOT NULL,
    anzeigename VARCHAR(200) NOT NULL,
    rolle      VARCHAR(20)  NOT NULL,
    aktiv      BOOLEAN      NOT NULL DEFAULT TRUE
);
