CREATE TABLE notizen (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inhalt      CLOB          NOT NULL,
    erstellt_am TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    team_id     BIGINT        REFERENCES teams(id) ON DELETE CASCADE,
    mitarbeiter_id BIGINT     REFERENCES mitarbeiter(id) ON DELETE CASCADE
);
