CREATE TABLE organisationen (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    erstellt_am TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO organisationen (name) VALUES ('Standard-Organisation');

-- Alle bestehenden Entitäten der Standard-Organisation zuweisen

ALTER TABLE teams ADD COLUMN organisation_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE teams ADD FOREIGN KEY (organisation_id) REFERENCES organisationen(id);

ALTER TABLE benutzer ADD COLUMN organisation_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE benutzer ADD FOREIGN KEY (organisation_id) REFERENCES organisationen(id);

ALTER TABLE mitarbeiter ADD COLUMN organisation_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE mitarbeiter ADD FOREIGN KEY (organisation_id) REFERENCES organisationen(id);

ALTER TABLE projekte ADD COLUMN organisation_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE projekte ADD FOREIGN KEY (organisation_id) REFERENCES organisationen(id);

ALTER TABLE aufgaben ADD COLUMN organisation_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE aufgaben ADD FOREIGN KEY (organisation_id) REFERENCES organisationen(id);

ALTER TABLE todos ADD COLUMN organisation_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE todos ADD FOREIGN KEY (organisation_id) REFERENCES organisationen(id);

ALTER TABLE notizen ADD COLUMN organisation_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE notizen ADD FOREIGN KEY (organisation_id) REFERENCES organisationen(id);
