CREATE TABLE meetings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id BIGINT        NOT NULL REFERENCES organisationen(id) ON DELETE CASCADE,
    titel           VARCHAR(200)  NOT NULL,
    datum           DATE          NOT NULL,
    notizen         CLOB,
    erstellt_am     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
