CREATE TABLE audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type  VARCHAR(50)  NOT NULL,
    entity_id    BIGINT,
    aktion       VARCHAR(20)  NOT NULL,
    benutzername VARCHAR(100) NOT NULL,
    zeitpunkt    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
